version: "3.5"

services:
  dev:
    container_name: pokemon-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    restart: always
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
